spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_soft1921?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
#    指定响应接口对应的xml文件所在目录
    mapper-locations: classpath:mapper/*.xml
#     实体类所在包
    type-aliases-package: top.yz.boot.mybatis.domain
    configuration:
#       mybatis开启驼峰式命名
      map-underscore-to-camel-case: true